-- delete from ProductOrder
-- delete from ClientOrder
-- delete from Product_Stock
-- delete from Product
-- delete from Account
-- drop table ProductOrder
-- drop table ClientOrder
-- drop table Product_Stock
-- drop table Product
-- drop table Account
-- 
-- ALTER TABLE Account DROP CONSTRAINT PK__Account__95DBD4629E394E5C